# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_internet_gateway.igw-09a4265d6d08afd54:
resource "aws_internet_gateway" "igw-09a4265d6d08afd54" {
  tags = {
    "Name" = "LatticeWorkshop"
  }
  tags_all = {
    "Name" = "LatticeWorkshop"
  }
  vpc_id = aws_vpc.vpc-0552cbf8549150e66.id
}
