# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table.rtb-06b5721bd6c57d41e:
resource "aws_route_table" "rtb-06b5721bd6c57d41e" {
  propagating_vgws = []
  route = [
    {
      carrier_gateway_id         = ""
      cidr_block                 = "0.0.0.0/0"
      core_network_arn           = ""
      destination_prefix_list_id = ""
      egress_only_gateway_id     = ""
      gateway_id                 = aws_internet_gateway.igw-095fc0e0738ebf326.id
      instance_id                = null
      ipv6_cidr_block            = null
      local_gateway_id           = ""
      nat_gateway_id             = ""
      network_interface_id       = ""
      transit_gateway_id         = ""
      vpc_endpoint_id            = ""
      vpc_peering_connection_id  = ""
    },
  ]
  tags = {
    "Name" = "LatticeWorkshop Public Routes"
  }
  tags_all = {
    "Name" = "LatticeWorkshop Public Routes"
  }
  vpc_id = aws_vpc.rates.id
}
