# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-090a5439929b42670__rtbassoc-0ee46c85d237dfdf8:
resource "aws_route_table_association" "subnet-090a5439929b42670__rtbassoc-0ee46c85d237dfdf8" {
  route_table_id = aws_route_table.rtb-01a5944d2392c4997.id
  subnet_id      = aws_subnet.subnet-090a5439929b42670.id
}
