# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_subnet.rates-pub2:
resource "aws_subnet" "rates-pub2" {
  assign_ipv6_address_on_creation                = false
  availability_zone                              = "eu-west-1b"
  cidr_block                                     = "10.0.1.0/24"
  enable_dns64                                   = false
  enable_resource_name_dns_a_record_on_launch    = false
  enable_resource_name_dns_aaaa_record_on_launch = false
  ipv6_native                                    = false
  map_public_ip_on_launch                        = true
  private_dns_hostname_type_on_launch            = "ip-name"
  tags = {
    "Name"                = "LatticeWorkshop Public Subnet2 Rates"
    "platform:visibility" = "public"
  }
  tags_all = {
    "Name"                = "LatticeWorkshop Public Subnet2 Rates"
    "platform:visibility" = "public"
  }
  vpc_id = aws_vpc.rates.id
}
