# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_nat_gateway.nat-05a99a78532c99404:
resource "aws_nat_gateway" "nat-05a99a78532c99404" {
  allocation_id     = aws_eip.eipalloc-01a2bb916364c472b.id
  connectivity_type = "public"
  subnet_id         = aws_subnet.rates-pub1.id
  tags = {
    "Name" = "LatticeWorkshop VPC"
  }
  tags_all = {
    "Name" = "LatticeWorkshop VPC"
  }
}
