# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# ../../scripts/052-get-iam-attached-role-policies.sh
# aws_iam_role_policy_attachment.r-testlatticebaseinfrawithapiserver-IamRoleLambdaCFn-151LS2SKHVS7X__AdministratorAccess:
resource "aws_iam_role_policy_attachment" "r-testlatticebaseinfrawithapiserver-IamRoleLambdaCFn-151LS2SKHVS7X__AdministratorAccess" {
  policy_arn = "arn:aws:iam::aws:policy/AdministratorAccess"
  role       = aws_iam_role.r-testlatticebaseinfrawithapiserver-IamRoleLambdaCFn-151LS2SKHVS7X.id
}
