# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.rates-pub1__rtbassoc-06ee06009ba37f594:
resource "aws_route_table_association" "rates-pub1__rtbassoc-06ee06009ba37f594" {
  route_table_id = aws_route_table.rtb-06b5721bd6c57d41e.id
  subnet_id      = aws_subnet.rates-pub1.id
}
