# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.r-testlatticebaseinfrawithapiserver-SSMRole-1CDQNUHP1D78M:
resource "aws_iam_role" "r-testlatticebaseinfrawithapiserver-SSMRole-1CDQNUHP1D78M" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "ec2.amazonaws.com"
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  force_detach_policies = false
  managed_policy_arns = [
    format("arn:aws:iam::%s:policy/InvokeLatticePolicy", data.aws_caller_identity.current.account_id),
    "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore",
    "arn:aws:iam::aws:policy/VPCLatticeReadOnlyAccess"
  ]
  max_session_duration = 3600
  name                 = "testlatticebaseinfrawithapiserver-SSMRole-1CDQNUHP1D78M"
  path                 = "/"
  tags                 = {}
  tags_all             = {}
}
