# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-08f8608099eb8cecb__rtbassoc-07d2c822039e2a815:
resource "aws_route_table_association" "subnet-08f8608099eb8cecb__rtbassoc-07d2c822039e2a815" {
  route_table_id = aws_route_table.rtb-0a39330951b04ddfa.id
  subnet_id      = aws_subnet.subnet-08f8608099eb8cecb.id
}
