# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_eip.eipalloc-01a2bb916364c472b:
resource "aws_eip" "eipalloc-01a2bb916364c472b" {
  network_border_group = "eu-west-1"
  public_ipv4_pool     = "amazon"
  tags = {
    "Name"                = "LatticeWorkshop VPC"
    "platform:visibility" = "public"
  }
  tags_all = {
    "Name"                = "LatticeWorkshop VPC"
    "platform:visibility" = "public"
  }
  domain = "vpc"
}
