# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_s3_bucket.b_superappsvcnetworklogs:
resource "aws_s3_bucket" "b_superappsvcnetworklogs" {
  bucket              = format("superappsvcnetworklog%s",data.aws_caller_identity.current.account_id)
  object_lock_enabled = false
  tags                = {}
  tags_all            = {}



}
