# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lb_listener.arn_aws_elasticloadbalancing__listener_app_testl-Paym:
resource "aws_lb_listener" "arn_aws_elasticloadbalancing__listener_app_testl-Paym" {
  load_balancer_arn = aws_lb.arn_aws_elasticloadbalancing__loadbalancer_app_testl-Paym.arn
  port              = 80
  protocol          = "HTTP"
  tags              = {}
  tags_all          = {}

  default_action {
    target_group_arn = aws_lb_target_group.arn_aws_elasticloadbalancing__targetgroup_payments-target-group.arn
    type             = "forward"
  }
}
