# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_key_pair.LatticeWorkshop:
resource "aws_key_pair" "LatticeWorkshop" {
  public_key = file("~/.ssh/id_rsa.pub")
  lifecycle {
    ignore_changes = [public_key]
  }
  key_name = "LatticeWorkshop"
  tags     = {}
  tags_all = {}
}
