# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_instance_profile.testlatticebaseinfrawithapiserver-InstanceProfile-sMdf0JeyeprL:
resource "aws_iam_instance_profile" "testlatticebaseinfrawithapiserver-InstanceProfile-sMdf0JeyeprL" {
  name     = "testlatticebaseinfrawithapiserver-InstanceProfile-sMdf0JeyeprL"
  path     = "/"
  role     = aws_iam_role.r-testlatticebaseinfrawithapiserver-SSMRole-1CDQNUHP1D78M.name
  tags     = {}
  tags_all = {}
}
