# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-080945eca077e4a32__rtbassoc-076639c164c3afab0:
resource "aws_route_table_association" "subnet-080945eca077e4a32__rtbassoc-076639c164c3afab0" {
  route_table_id = aws_route_table.rtb-07490a3a02fdf0258.id
  subnet_id      = aws_subnet.subnet-080945eca077e4a32.id
}
