# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_instance.i-0d2177a70c5cd8982:
resource "aws_instance" "i-0d2177a70c5cd8982" {
  ami                                  = "ami-09c4fa265be945f47"
  associate_public_ip_address          = false
  availability_zone                    = "eu-west-1a"
  disable_api_stop                     = false
  disable_api_termination              = false
  ebs_optimized                        = false
  get_password_data                    = false
  hibernation                          = false
  iam_instance_profile                 = aws_iam_instance_profile.testlatticebaseinfrawithapiserver-InstanceProfile-sMdf0JeyeprL.id
  instance_initiated_shutdown_behavior = "stop"
  instance_type                        = "t3.small"
  key_name                             = "LatticeWorkshop"
  monitoring                           = false
  placement_partition_number           = 0
  secondary_private_ips                = []
  security_groups                      = []
  source_dest_check                    = true
  # client private subnet (SSM comms via NAT)
  subnet_id                            = aws_subnet.subnet-063b5eacd2d6cb0d3.id
  tags = {
    "Name"        = "LatticeWorkshop InstanceClient2"
    "Patch Group" = "AccountGuardian-PatchGroup-DO-NOT-DELETE"
  }
  tags_all = {
    "Name"        = "LatticeWorkshop InstanceClient2"
    "Patch Group" = "AccountGuardian-PatchGroup-DO-NOT-DELETE"
  }
  tenancy = "default"
  lifecycle {
    ignore_changes = [user_data_replace_on_change, associate_public_ip_address, user_data, user_data_base64]
  }
  user_data_base64 = filebase64sha256("i-0d2177a70c5cd8982.sh")
  vpc_security_group_ids = [
    aws_security_group.sg-03d872da0ef11f465.id,
  ]

  capacity_reservation_specification {
    capacity_reservation_preference = "open"
  }

  cpu_options {
    core_count       = 1
    threads_per_core = 2
  }

  credit_specification {
    cpu_credits = "unlimited"
  }

  enclave_options {
    enabled = false
  }

  maintenance_options {
    auto_recovery = "default"
  }

  metadata_options {
    http_endpoint               = "enabled"
    http_put_response_hop_limit = 1
    http_tokens                 = "optional"
    instance_metadata_tags      = "disabled"
  }

  private_dns_name_options {
    enable_resource_name_dns_a_record    = false
    enable_resource_name_dns_aaaa_record = false
    hostname_type                        = "ip-name"
  }

  root_block_device {
    delete_on_termination = true
    encrypted             = false
    iops                  = 3000
    tags                  = {}
    throughput            = 125
    volume_size           = 8
    volume_type           = "gp3"
  }
  user_data_replace_on_change = false
}
