# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_internet_gateway.igw-07df5f22959160af7:
resource "aws_internet_gateway" "igw-07df5f22959160af7" {
  tags = {
    "Name" = "LatticeWorkshop"
  }
  tags_all = {
    "Name" = "LatticeWorkshop"
  }
  vpc_id = aws_vpc.vpc-06977ec8dcb8f6e81.id
}
