# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lb_target_group.arn_aws_elasticloadbalancing__targetgroup_payments-target-group:
resource "aws_lb_target_group" "arn_aws_elasticloadbalancing__targetgroup_payments-target-group" {
  deregistration_delay              = "300"
  ip_address_type                   = "ipv4"
  load_balancing_algorithm_type     = "round_robin"
  load_balancing_cross_zone_enabled = "use_load_balancer_configuration"
  name                              = "payments-target-group"
  port                              = 4242
  protocol                          = "HTTP"
  protocol_version                  = "HTTP1"
  slow_start                        = 0
  tags                              = {}
  tags_all                          = {}
  target_type                       = "instance"
  vpc_id                            = aws_vpc.payments.id

  health_check {
    enabled             = true
    healthy_threshold   = 5
    interval            = 30
    matcher             = "200"
    path                = "/"
    port                = "traffic-port"
    protocol            = "HTTP"
    timeout             = 5
    unhealthy_threshold = 2
  }

  stickiness {
    cookie_duration = 86400
    enabled         = false
    type            = "lb_cookie"
  }

}
