# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-08ff2bb366da64167__rtbassoc-06b36fe26a9c3cece:
resource "aws_route_table_association" "subnet-08ff2bb366da64167__rtbassoc-06b36fe26a9c3cece" {
  route_table_id = aws_route_table.rtb-07490a3a02fdf0258.id
  subnet_id      = aws_subnet.subnet-08ff2bb366da64167.id
}
