# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-063b5eacd2d6cb0d3__rtbassoc-0c659808403c730d7:
resource "aws_route_table_association" "subnet-063b5eacd2d6cb0d3__rtbassoc-0c659808403c730d7" {
  route_table_id = aws_route_table.rtb-074aa48c67f043297.id
  subnet_id      = aws_subnet.subnet-063b5eacd2d6cb0d3.id
}
