# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-01e8f537bc66d049a__rtbassoc-0b6a52b8d1af5d7c5:
resource "aws_route_table_association" "subnet-01e8f537bc66d049a__rtbassoc-0b6a52b8d1af5d7c5" {
  route_table_id = aws_route_table.rtb-01a5944d2392c4997.id
  subnet_id      = aws_subnet.subnet-01e8f537bc66d049a.id
}
