# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-0b30aa46e410c903d__rtbassoc-06e72ed49c8a52107:
resource "aws_route_table_association" "subnet-0b30aa46e410c903d__rtbassoc-06e72ed49c8a52107" {
  route_table_id = aws_route_table.rtb-08c2fe56e72e4e9cc.id
  subnet_id      = aws_subnet.subnet-0b30aa46e410c903d.id
}
