# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lb_listener.arn_aws_elasticloadbalancing_eu-west-1_566972129213_listener_app_testl-Payme-UNPBI1NL9VPA_5ee6b15c48e1c3fa_f3646061e81dba93:
resource "aws_lb_listener" "arn_aws_elasticloadbalancing_eu-west-1_566972129213_listener_app_testl-Payme-UNPBI1NL9VPA_5ee6b15c48e1c3fa_f3646061e81dba93" {
  load_balancer_arn = aws_lb.arn_aws_elasticloadbalancing_eu-west-1_566972129213_loadbalancer_app_testl-Payme-UNPBI1NL9VPA_5ee6b15c48e1c3fa.arn
  port              = 80
  protocol          = "HTTP"
  tags              = {}
  tags_all          = {}

  default_action {
    target_group_arn = aws_lb_target_group.arn_aws_elasticloadbalancing_eu-west-1_566972129213_targetgroup_payments-target-group_8fa7228052d0bd8c.arn
    type             = "forward"
  }
}
