# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group.sg-04c2eaaaf6f61e5a1:
resource "aws_security_group" "sg-04c2eaaaf6f61e5a1" {
  description = "Allow all for workshop"
  tags        = {}
  tags_all    = {}
  vpc_id      = aws_vpc.rates.id
}
