# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_iam_role.r-testlatticebaseinfrawithapiserver-IamRoleLambdaCFn-151LS2SKHVS7X:
resource "aws_iam_role" "r-testlatticebaseinfrawithapiserver-IamRoleLambdaCFn-151LS2SKHVS7X" {
  assume_role_policy = jsonencode(
    {
      Statement = [
        {
          Action = "sts:AssumeRole"
          Effect = "Allow"
          Principal = {
            Service = "lambda.amazonaws.com"
          }
        },
      ]
      Version = "2012-10-17"
    }
  )
  description           = "Provides permissions for Lambda to deploy VPC/CloudWAN resources in Primary region."
  force_detach_policies = false
  managed_policy_arns = [
    "arn:aws:iam::aws:policy/AdministratorAccess",
  ]
  max_session_duration = 3600
  name                 = "testlatticebaseinfrawithapiserver-IamRoleLambdaCFn-151LS2SKHVS7X"
  path                 = "/"
  tags                 = {}
  tags_all             = {}
}
