# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table.rtb-08c2fe56e72e4e9cc:
resource "aws_route_table" "rtb-08c2fe56e72e4e9cc" {
  propagating_vgws = []
  route = [
    {
      carrier_gateway_id         = ""
      cidr_block                 = "0.0.0.0/0"
      core_network_arn           = ""
      destination_prefix_list_id = ""
      egress_only_gateway_id     = ""
      gateway_id                 = aws_internet_gateway.igw-0f72e5eff01eaf04b.id
      instance_id                = null
      ipv6_cidr_block            = null
      local_gateway_id           = ""
      nat_gateway_id             = ""
      network_interface_id       = ""
      transit_gateway_id         = ""
      vpc_endpoint_id            = ""
      vpc_peering_connection_id  = ""
    },
  ]
  tags = {
    "Name" = "LatticeWorkshop Public Routes"
  }
  tags_all = {
    "Name" = "LatticeWorkshop Public Routes"
  }
  vpc_id = aws_vpc.payments.id
}
