# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# ../../scripts/get-iam-policies.sh
# aws_iam_policy.p_InvokeLatticePolicy:
resource "aws_iam_policy" "p_InvokeLatticePolicy" {
  description = "Managed policy for a instances to invoke vpc-lattice"
  name        = "InvokeLatticePolicy"
  path        = "/"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "vpc-lattice-svcs:Invoke",
          ]
          Effect     = "Allow"
          "Resource" = "*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  tags     = {}
  tags_all = {}
}
