# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_lambda_function.LatticeReservationLambda:
resource "aws_lambda_function" "LatticeReservationLambda" {
  architectures = [
    "x86_64",
  ]
  function_name = "LatticeReservationLambda"
  handler       = "index.lambda_handler"
  lifecycle {
    ignore_changes = [filename]
  }
  filename                       = "LatticeReservationLambda.zip"
  layers                         = []
  memory_size                    = 128
  package_type                   = "Zip"
  reserved_concurrent_executions = -1
  role                           = aws_iam_role.r-Lattice-Lambda-Role.arn
  runtime                        = "python3.8"
  skip_destroy                   = false
  source_code_hash               = filebase64sha256("LatticeReservationLambda.zip")
  tags                           = {}
  tags_all                       = {}
  timeout                        = 240

  ephemeral_storage {
    size = 512
  }

  tracing_config {
    mode = "PassThrough"
  }

  vpc_config {
    security_group_ids = [
      aws_security_group.sg-067dfe4dec422ce60.id,
    ]
    subnet_ids = [
      aws_subnet.subnet-04e4d0bf90c44cd56.id,
      aws_subnet.subnet-08f8608099eb8cecb.id,
    ]
  }
}
