# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_internet_gateway.igw-095fc0e0738ebf326:
resource "aws_internet_gateway" "igw-095fc0e0738ebf326" {
  tags = {
    "Name" = "LatticeWorkshop"
  }
  tags_all = {
    "Name" = "LatticeWorkshop"
  }
  vpc_id = aws_vpc.rates.id
}
