# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# ../../scripts/052-get-iam-attached-role-policies.sh
# aws_iam_role_policy_attachment.r-Lattice-Lambda-Role__Lattice-Lambda-Policy:
resource "aws_iam_role_policy_attachment" "r-Lattice-Lambda-Role__Lattice-Lambda-Policy" {
  policy_arn = aws_iam_policy.p_Lattice-Lambda-Policy.arn
  role       = aws_iam_role.r-Lattice-Lambda-Role.id
}
