# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_s3_bucket.b_superappsvcnetworklogs566972129213:
resource "aws_s3_bucket" "b_superappsvcnetworklogs566972129213" {
  bucket              = "superappsvcnetworklogs566972129213"
  object_lock_enabled = false
  tags                = {}
  tags_all            = {}



}
