# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_autoscaling_group.testlatticebaseinfrawithapiserver-PaymentsASG-1409F0PXQNT6K:
resource "aws_autoscaling_group" "testlatticebaseinfrawithapiserver-PaymentsASG-1409F0PXQNT6K" {
  availability_zones = [
    "eu-west-1a",
    "eu-west-1b",
  ]
  capacity_rebalance        = false
  default_cooldown          = 300
  default_instance_warmup   = 0
  desired_capacity          = 1
  enabled_metrics           = []
  health_check_grace_period = 0
  health_check_type         = "EC2"
  load_balancers            = []
  max_instance_lifetime     = 0
  max_size                  = 1
  metrics_granularity       = "1Minute"
  min_size                  = 1
  name                      = "testlatticebaseinfrawithapiserver-PaymentsASG-1409F0PXQNT6K"
  protect_from_scale_in     = false
  service_linked_role_arn   = "arn:aws:iam::566972129213:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling"
  suspended_processes       = []
  target_group_arns = [
    "arn:aws:elasticloadbalancing:eu-west-1:566972129213:targetgroup/payments-target-group/8fa7228052d0bd8c",
  ]
  termination_policies = []

  launch_template {
    #name    = aws_launch_template.lt-05a68757283c6e194.name
    name    = aws_launch_template.payments.name
    version = "1"
  }

  tag {
    key                 = "Name"
    propagate_at_launch = true
    value               = "LatticeWorkshop Payments"
  }
}
