# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-054190ca217d10c51__rtbassoc-05fdb01bf7d59aac2:
resource "aws_route_table_association" "subnet-054190ca217d10c51__rtbassoc-05fdb01bf7d59aac2" {
  route_table_id = aws_route_table.rtb-06b5721bd6c57d41e.id
  subnet_id      = aws_subnet.subnet-054190ca217d10c51.id
}
