# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.subnet-03711fd0b665b596c__rtbassoc-08042e001fe4bae0b:
resource "aws_route_table_association" "subnet-03711fd0b665b596c__rtbassoc-08042e001fe4bae0b" {
  route_table_id = aws_route_table.rtb-01a5944d2392c4997.id
  subnet_id      = aws_subnet.subnet-03711fd0b665b596c.id
}
