# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_security_group.sg-08f0a156dbeb9724b:
resource "aws_security_group" "sg-08f0a156dbeb9724b" {
  description = "Allow all for workshop"
  tags        = {}
  tags_all    = {}
  vpc_id      = aws_vpc.payments.id
}
