# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# ../../scripts/get-iam-policies.sh
# aws_iam_policy.p_Lattice-Lambda-Policy:
resource "aws_iam_policy" "p_Lattice-Lambda-Policy" {
  description = "Managed policy for a Lambda function launched by CloudFormation"
  name        = "Lattice-Lambda-Policy"
  path        = "/"
  policy = jsonencode(
    {
      Statement = [
        {
          Action = [
            "ec2:DescribeNetworkInterfaces",
            "ec2:CreateNetworkInterface",
            "ec2:DeleteNetworkInterface",
            "ec2:DescribeInstances",
            "ec2:AttachNetworkInterface",
            "vpc-lattice-svcs:Invoke",
          ]
          Effect     = "Allow"
          "Resource" = "*"
        },
        {
          Action = [
            "logs:CreateLogStream",
            "logs:PutLogEvents",
          ]
          Effect     = "Allow"
          "Resource" = "arn:aws:logs:eu-west-1:566972129213:log-group:/aws/lambda/LatticeReservationLambda:*"
        },
        {
          Action = [
            "logs:CreateLogGroup",
          ]
          Effect     = "Allow"
          "Resource" = "arn:aws:logs:eu-west-1:566972129213:*"
        },
      ]
      Version = "2012-10-17"
    }
  )
  tags     = {}
  tags_all = {}
}
