# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_route_table_association.payments-pub2__rtbassoc-0daa1c5a7b1a8542b:
resource "aws_route_table_association" "payments-pub2__rtbassoc-0daa1c5a7b1a8542b" {
  route_table_id = aws_route_table.rtb-08c2fe56e72e4e9cc.id
  subnet_id      = aws_subnet.payments-pub2.id
}
