# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_autoscaling_group.testlatticebaseinfrawithapiserver-RatesASG-16HVW360AFWPF:
resource "aws_autoscaling_group" "testlatticebaseinfrawithapiserver-RatesASG-16HVW360AFWPF" {
  availability_zones = [
    "eu-west-1a",
    "eu-west-1b",
  ]
  capacity_rebalance        = false
  default_cooldown          = 300
  default_instance_warmup   = 0
  desired_capacity          = 1
  enabled_metrics           = []
  health_check_grace_period = 0
  health_check_type         = "EC2"
  load_balancers            = []
  max_instance_lifetime     = 0
  max_size                  = 1
  metrics_granularity       = "1Minute"
  min_size                  = 1
  name                      = "testlatticebaseinfrawithapiserver-RatesASG-16HVW360AFWPF"
  protect_from_scale_in     = false
  service_linked_role_arn   = "arn:aws:iam::566972129213:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling"
  suspended_processes       = []
  target_group_arns         = []
  termination_policies      = []

  launch_template {
    #name    = aws_launch_template.lt-0692233e69efb7d98.name
    name    = aws_launch_template.rates.name
    version = "1"
  }

  tag {
    key                 = "Name"
    propagate_at_launch = true
    value               = "LatticeWorkshop Rates"
  }
}
