# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpclattice_service_network_service_association.snsa-0864747d2770172e6:
resource "aws_vpclattice_service_network_service_association" "snsa-0864747d2770172e6" {
  service_identifier         = aws_vpclattice_service.svc-01140bc6b2d1ae15b.id
  service_network_identifier = aws_vpclattice_service_network.sn-09c95c9b9ab29e33e.id
  tags                       = {}
  tags_all                   = {}
}
