# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpclattice_service.svc-06f9423290d1e2bb1:
resource "aws_vpclattice_service" "svc-06f9423290d1e2bb1" {
  auth_type = "NONE"
  name      = "parking"
  tags      = {}
  tags_all  = {}
}

output "svc-parking-dns" {
value=aws_vpclattice_service.svc-06f9423290d1e2bb1.dns_entry[0].domain_name
}
