# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpclattice_target_group.tg-00cd21289524685dd:
resource "aws_vpclattice_target_group" "rates-tg" {
  name     = "rates-tg"
  tags     = {}
  tags_all = {}
  type     = "INSTANCE"

  config {
    port             = 4242
    protocol         = "HTTP"
    protocol_version = "HTTP1"
    vpc_identifier   = data.aws_vpc.rates.id
  }
}
