# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpclattice_listener.svc-06f9423290d1e2bb1__listener-07a3088ef9edf4330:
resource "aws_vpclattice_listener" "svc-06f9423290d1e2bb1__listener-07a3088ef9edf4330" {
  name               = "http-80"
  port               = 80
  protocol           = "HTTP"
  service_arn        = aws_vpclattice_service.svc-06f9423290d1e2bb1.arn
  service_identifier = aws_vpclattice_service.svc-06f9423290d1e2bb1.id
  tags               = {}
  tags_all           = {}

  default_action {
    forward {
      target_groups {
        target_group_identifier = aws_vpclattice_target_group.tg-00cd21289524685dd.id
        weight                  = 1
      }
    }
  }
}
