# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpclattice_service_network.sn-09c95c9b9ab29e33e:
resource "aws_vpclattice_service_network" "sn-09c95c9b9ab29e33e" {
  auth_type = "NONE"
  name      = "superappsvcnetwork"
  tags      = {}
  tags_all  = {}
}
