# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpclattice_service_network_vpc_association.snva-015e59dfe350453de:
resource "aws_vpclattice_service_network_vpc_association" "snva-015e59dfe350453de" {
  security_group_ids = [
    data.aws_security_group.clients-sg.id,
  ]
  service_network_identifier = aws_vpclattice_service_network.sn-09c95c9b9ab29e33e.id
  tags                       = {}
  tags_all                   = {}
  vpc_identifier             = data.aws_vpc.clients.id
}
