# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpclattice_service_network_service_association.snsa-08375ab233f06eeb3:
resource "aws_vpclattice_service_network_service_association" "snsa-08375ab233f06eeb3" {
  service_identifier         = aws_vpclattice_service.svc-06f9423290d1e2bb1.id
  service_network_identifier = aws_vpclattice_service_network.sn-09c95c9b9ab29e33e.id
  tags                       = {}
  tags_all                   = {}
}
