# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpclattice_listener.svc-01140bc6b2d1ae15b__listener-0d9bab3230fb40114:
resource "aws_vpclattice_listener" "svc-01140bc6b2d1ae15b__listener-0d9bab3230fb40114" {
  name               = "https-443"
  port               = 443
  protocol           = "HTTPS"
  service_arn        = aws_vpclattice_service.svc-01140bc6b2d1ae15b.arn
  service_identifier = aws_vpclattice_service.svc-01140bc6b2d1ae15b.id
  tags               = {}
  tags_all           = {}

  default_action {
    forward {
      target_groups {
        target_group_identifier = aws_vpclattice_target_group.tg-0db3a282d7c581867.id
        weight                  = 1
      }
    }
  }
}
