# File generated by aws2tf see https://github.com/aws-samples/aws2tf
# aws_vpclattice_target_group.tg-0db3a282d7c581867:
resource "aws_vpclattice_target_group" "tg-0db3a282d7c581867" {
  name     = "reservation-tg"
  tags     = {}
  tags_all = {}
  type     = "LAMBDA"

}
